### ISSUE TITLE
explicit differences with nix/guix in README?

### ISSUE THREAD

**Issue by chessai** [andrewchambers/hermes#34]
Firstly, thanks for the cool project!

The README states that there are some key differences between hermes and nix/guix, but is a bit vague in how. The next section sort-of helps in describing hermes, but not differences between hermes and other approaches to dependency management.

**Comment by andrewchambers** [comment]
Some of this is evolving, but some differences at the moment:

- No build daemon.
- (Imo) easier to learn packaging language, based on janet.
- Streamlined user interface.
- Emphasis one allowing packages to be installed directly from url's. E.g. directly from a github link,
- Core package respository based on musllibc instead of glibc.

We can be more explicit further down the project I suppose.

edit: Working on some pages to explain in a better way.

**Comment by andrewchambers** [comment]
As an example of url imports:

https://github.com/andrewchambers/hermes/blob/493271d5f780997e63a0554393da5038be245c12/support/dev-env.hpkg#L1

Overall if you are familiar with nix or guix, it is similar I suppose.

**Comment by andrewchambers** [comment]
I have added a page https://github.com/andrewchambers/hermes/blob/master/doc/compared-to-nix-and-guix.md

**Comment by chessai** [comment]
Awesome, thanks!
